## **Teorema 1**

Si $A$ es una matriz $n\times n$ tal que $\Vert A\Vert <1$, entonces $A^{-1}$ es inversible y
	$$(I-A)^{-1} = \sum_{k=0}^{\infty}A^{k}$$

In [16]:
"""
Series de neuman (con la norma del máximo)


s: almacena A + A^1 + A^2 + ... + A^{MAX_ITERATIONS}
"""

import numpy as np

def max_norm(A):
    n = np.shape(A)[0]
    s = sum(A[0,:])
    for k in range(1,n):
        if s < sum(A[k,:]):
            s = sum(A[k,:])
            
    return s

def neumann(A, MAX_ITERATIONS=1000):
    if max_norm(A) < 1:
        n = np.shape(A)[0]
        s = np.identity(n)
        for k in range(MAX_ITERATIONS):
            s += A
            A = np.dot(A, A)
            
        return s
    else:
        print("La matriz\n{}\n puede no ser inversible".format(I-A))
                

**Ejercicio de Aplicación**  
Use la se serie  de Neumann para calcular la inversa de la matriz.
$$B = \begin{bmatrix}
0.9 &-0.2 &-0.3\\
0.1 &1.0  &-0.1\\
0.3 &0.2  &1.1
\end{bmatrix}$$
Use la norma del máximo.

In [17]:
"""
Ilustración de solución:

Si A = I-B, tenemos que ||A||=0.6 <1, luego (I-A)^{-1} = B^{-1} = I + A +A^2 +A^3 + ....  
"""

import numpy as np

B = np.array([0.9, -0.2, -0.3, 0.1 ,1.0, -0.1, 0.3, 0.2, 1.1], dtype=np.float64).reshape(3,3)

n = np.shape(B)[0]
A = np.identity(n)-B

invB = neumann(A) # inversa de B

print("B^(-1) = \n{}\n".format(invB))
print("BxB^(-1) =\n{}".format(B, invB, np.dot(B, invB)))



B^(-1) = 
[[ 1.01217284  0.16486913  0.31756543]
 [-0.13513087  0.96486913  0.06486913]
 [-0.28243457 -0.23513087  0.81217284]]

BxB^(-1) =
[[ 0.9 -0.2 -0.3]
 [ 0.1  1.  -0.1]
 [ 0.3  0.2  1.1]]
